"""The v3 perf budget and the six golden floors.

Two things live here. The first is the perf test: `generate_floor_v3`
has to draw AND validate a floor in p95 <= 40 ms at each of the four
sizes of PLAN.md section 3. It is measured the way
`docs/research/endless-e0.md` measured the v2 generator, so the numbers
are comparable with the table in that document: 200 seeds, ONE
`generate_floor_v3` call per sample, `time.perf_counter()` around the
call, and nearest-rank percentiles, `sorted[floor(p * (n - 1))]`.

The second is the goldens. The six files under `tests/golden/floors/v3/`
are FloorPlans drawn by `vefr.delve_v3` and committed, named
`<floor_kind>__<seed>__<w>x<h>.json`. They pin the generator: a floor key
that stops drawing the same plan, and any change to the layout stream,
shows up as a golden diff instead of as a surprise at run time.

A golden is regenerated BY HAND, only when the layout stream deliberately
changes, and never to make a failing test pass. Each file is
`json.dumps(plan, sort_keys=True, indent=2)` plus one trailing newline, so
a diff is readable and a change is reviewable. To rewrite all six, from
the repo root:

    uv run python -c "import json,pathlib,runpy;from vefr import delve_v3;m=runpy.run_path('tests/test_floor_perf.py');[pathlib.Path(f'tests/golden/floors/v3/{k}__{s}__{w}x{h}.json').write_text(json.dumps(delve_v3.generate_floor_v3(s,(w,h),m['section'](f'cellar-{k}',m['ROOM_QUOTA'][w]),k),sort_keys=True,indent=2)+chr(10),encoding='utf-8') for k,s,w,h in m['GOLDENS']]"

That one line IS the whole writer - there is no script and no `__main__`
block, so the goldens can only be rewritten by a person who means to.
Read the resulting diff before committing it: every changed line is a
generator change, not noise.
"""

from __future__ import annotations

import copy
import json
from math import floor
from pathlib import Path
import time

import pytest

from vefr import delve_v3


# The four sizes of PLAN.md section 3, with the room quota each carries,
# and the quota keyed by width for the goldens to look up.
SIZES = [(48, 32, 16), (64, 48, 18), (96, 64, 24), (128, 96, 32)]
ROOM_QUOTA = {w: rooms for w, h, rooms in SIZES}

# The budget of PLAN.md section 3: generate + validate, p95 over 200 seeds.
# A hard gate, not an advisory. The worst size measures ~2 ms, so this
# sits under 20x headroom and has never been close.
BUDGET_MS = 40.0

# The sweep's own seeds, so the perf sample and the property sweep of
# `tests/test_floor_v3_properties.py` read the same 200 floors per size.
SEEDS = [f"sweep-{i}" for i in range(200)]

# Every character a row may carry, and the subset the hero can stand on.
ALPHABET = frozenset("#.ud")
WALKABLE = frozenset(".ud")

# The six goldens as (floor kind, seed, w, h). All four sizes of section 3
# and all four floor kinds, so a size or a kind that stops drawing the same
# plan is caught by one of the six. Two sizes carry a second kind, which is
# what a kind that stops drawing its own plan is caught by: the pair at one
# size is two different floor keys and two different floors, so a kind, a
# seed or a size that moves is caught by a diff in one of the six. What that
# pair does NOT hold is the section half of the key on its own - the two
# members differ in their seed as well as in their Section id, so the pair
# cannot say which half of `run_seed/section.id/cycle/k` did it.
# `test_the_section_half_of_the_key_alone_moves_the_floor` below is the test
# that says it: one seed, one size, one kind, two Section ids. The floor kind
# is not in the key - `run_seed/section.id/cycle/k` is - so a kind reaches the
# floor through the plan and pop stages instead. The last golden is the stress
# size on the only kind that can come back `waypoint: true`.
GOLDENS = [
    ("normal", "sweep-0", 48, 32),
    ("treasure", "sweep-1", 48, 32),
    ("normal", "sweep-2", 64, 48),
    ("infested", "sweep-3", 64, 48),
    ("normal", "sweep-4", 96, 64),
    ("hub", "sweep-5", 128, 96),
]

# Where the goldens live, relative to this file rather than the cwd, so a
# pytest run from anywhere finds the same six.
GOLDEN_DIR = Path(__file__).resolve().parent / "golden" / "floors" / "v3"


def section(id: str, rooms: int) -> dict:
    """A valid Section pack for one floor kind and one size's room quota.

    The same shape the v3 property sweep uses, because the same pack and
    the same floor key are what make these floors comparable with it. The
    floor key carries the section id, so `cellar-normal` and
    `cellar-treasure` are two different floors out of the same seed.
    `rooms` is `[quota, quota]` so the quota is exact rather than sampled,
    and there is no `chest_values` table, so by the API contract every
    chest is worth 1.
    """
    return {
        "section": 1,
        "id": id,
        "rooms": [rooms, rooms],
        "families": [
            {"family": "rat", "weight": 5, "depth": [1, 6]},
            {"family": "moth", "weight": 3, "depth": [1, 9]},
            {"family": "beetle", "weight": 2, "depth": [3, 9]},
        ],
        "elites": {"per_floor": [1, 2], "affixes": ["big", "quick", "glowing"]},
        "groups": {"per_floor": [1, 2], "minions": [2, 3]},
        "loot": {"tier": 1},
        "pois": ["the drowned well", "the ash alcove", "the rusted grate"],
        "warden": "ashwing",
        "vault": "vault-cellar",
    }


# --------------------------------------------------------------- the perf test


def _percentile(samples: list[float], p: float) -> float:
    """The nearest-rank percentile `sorted[floor(p * (n - 1))]`.

    The exact rule `docs/research/endless-e0.md` states, so a number here
    reads against the v2 table in that document without a conversion.
    """
    ordered = sorted(samples)
    return ordered[floor(p * (len(ordered) - 1))]


def _samples(w: int, h: int, rooms: int) -> list[float]:
    """One `generate_floor_v3` call per sweep seed, in milliseconds.

    The pack is copied per call so a generator that mutated the pack it
    was handed could not show up here as a timing change, and the copy is
    made OUTSIDE the timed region: what is measured is the generator, not
    a deepcopy.

    The interpreter is warm before the first sample. `delve_v3` was
    imported at module load, and one throwaway floor is drawn per size
    below, so neither the import nor any other one-time cost - the
    bytecode, the first `prng` of a stream name, the venv's lazy imports
    - can land inside a timed sample.
    """
    pack = section("cellar-normal", rooms)
    delve_v3.generate_floor_v3("warmup", (w, h), copy.deepcopy(pack), "normal")
    samples: list[float] = []
    for seed in SEEDS:
        call_pack = copy.deepcopy(pack)
        start = time.perf_counter()
        delve_v3.generate_floor_v3(seed, (w, h), call_pack, "normal")
        samples.append((time.perf_counter() - start) * 1000.0)
    return samples


@pytest.mark.parametrize("w, h, rooms", SIZES, ids=[f"{w}x{h}" for w, h, _ in SIZES])
def test_generation_p95_within_budget(w, h, rooms):
    """Draw + validate a floor in p95 <= 40 ms, at one size, over 200 seeds.

    Parametrised, so each size is its own test id and its own number: a
    regression is named by the size that caused it rather than hidden in
    an average over four.
    """
    samples = _samples(w, h, rooms)
    p50 = _percentile(samples, 0.50)
    p95 = _percentile(samples, 0.95)
    worst = max(samples)
    print(
        f"\n{w}x{h}x{rooms} normal: p50 {p50:.3f} ms, p95 {p95:.3f} ms, "
        f"max {worst:.3f} ms over {len(samples)} seeds "
        f"({BUDGET_MS / p95:.0f}x under the {BUDGET_MS:.0f} ms budget)"
    )
    assert p95 <= BUDGET_MS, (
        f"{w}x{h}x{rooms}: p95 is {p95:.3f} ms over {len(samples)} seeds, the "
        f"budget is {BUDGET_MS:.0f} ms; p50 {p50:.3f} ms, max {worst:.3f} ms"
    )


# -------------------------------------------------------------- the goldens


def _golden_paths() -> list[Path]:
    """The committed goldens, in filename order so a failure is repeatable."""
    return sorted(GOLDEN_DIR.glob("*.json"))


def _from_name(path: Path) -> tuple[str, str, int, int]:
    """`(kind, seed, w, h)` out of a `<kind>__<seed>__<w>x<h>.json` name.

    The kind and the seed are the caller's half of the arguments and the
    plan itself does not carry them, so they live in the filename. The
    size is there too, but the goldens regenerate from the size IN the
    file, and the filename's size is only checked against it.
    """
    kind, seed, size = path.stem.split("__")
    w, h = size.split("x")
    return kind, seed, int(w), int(h)


# What a golden mismatch means, and is not: the two legitimate reasons to
# rewrite a golden, both of which want a human reading the diff.
REGENERATE_HINT = (
    ". If the layout stream changed on purpose, rewrite the goldens by hand with "
    "the one-liner in this module's docstring and review the diff; if it did not, "
    "this is a generator regression"
)


def _difference(stored: str, drawn: dict) -> str:
    """Where the golden and the fresh draw part company, as one sentence.

    Both sides are the same plan in the same `indent=2` form, so the first
    differing line names the row, the room or the spawn that moved.
    """
    lines = json.dumps(drawn, sort_keys=True, indent=2).splitlines()
    for number, (left, right) in enumerate(zip(stored.splitlines(), lines), 1):
        if left != right:
            return f"line {number} differs: golden {left!r}, fresh draw {right!r}"
    return "the two are line for line identical, so only the formatting differs"


def test_goldens_match_a_fresh_draw():
    """Every committed golden is byte-for-byte what the generator draws today.

    The floor kind and the seed come from the filename, the size and
    everything else from the file's own contents, so a golden is checked
    by regenerating exactly the arguments that wrote it.

    Two comparisons, and the second is the stronger one. The plan is
    compared as the canonical `json.dumps(..., sort_keys=True)` of both
    sides, so neither key order nor spacing can fake a match; then the
    file's exact bytes are compared against the same plan in the
    `indent=2` form the goldens are committed in plus one trailing
    newline, so a hand edit that means nothing to the plan is still
    caught.
    """
    paths = _golden_paths()
    assert paths, f"no goldens under {GOLDEN_DIR}"
    for path in paths:
        kind, seed, named_w, named_h = _from_name(path)
        stored_text = path.read_text(encoding="utf-8")
        stored = json.loads(stored_text)
        w, h = stored["w"], stored["h"]
        if (named_w, named_h) != (w, h):
            pytest.fail(
                f"{path.name} is named {named_w}x{named_h} but holds a {w}x{h} floor; "
                "rename the file to match its contents"
            )
        pack = section(f"cellar-{kind}", ROOM_QUOTA[w])
        drawn = delve_v3.generate_floor_v3(seed, (w, h), pack, kind)
        if json.dumps(drawn, sort_keys=True) != json.dumps(stored, sort_keys=True):
            pytest.fail(
                f"{path.name}: a fresh draw of {seed}/{kind} is not the golden. "
                f"{_difference(stored_text, drawn)}{REGENERATE_HINT}"
            )
        if stored_text != json.dumps(drawn, sort_keys=True, indent=2) + "\n":
            pytest.fail(
                f"{path.name}: the plan matches, but the file is not the canonical "
                f"golden form. {_difference(stored_text, drawn)}{REGENERATE_HINT}"
            )


def test_the_section_half_of_the_key_alone_moves_the_floor():
    """One seed, one size, one kind, two Section ids: two floors.

    The floor key is `run_seed/section.id/cycle/k`, so the section id is one
    of the four things that names a floor. This holds everything else fixed -
    same seed, same size, same floor kind, same `depth` and `cycle` - and
    changes only `id`, so the floor that moves can only be the key's section
    half moving.

    It is the half the golden pairs above cannot show: those differ in their
    seed as well as in their Section id, so a diff there says "the key
    changed" and not "the section half is in the key".

    Pinned at one seed per size, and on both sides of the cap: the floors are
    allowed to be equal here ONLY if a floor cannot be drawn at all, which
    would be a broken fixture rather than a floor worth asserting about.
    """
    for w, h, rooms in SIZES:
        seed = SEEDS[0]
        cellar = delve_v3.generate_floor_v3(
            seed, (w, h), section("cellar-normal", rooms), "normal")
        vault = delve_v3.generate_floor_v3(
            seed, (w, h), section("cellar-vault", rooms), "normal")
        where = f"seed {seed} at {w}x{h}"
        if cellar["gen"] != 3 or vault["gen"] != 3:
            pytest.fail(f"{where}: one of the two fell back to v2 geometry, so "
                        "the pair proves nothing about the section half")
        if json.dumps(cellar, sort_keys=True) == json.dumps(vault, sort_keys=True):
            pytest.fail(
                f"{where}: `cellar-normal` and `cellar-vault` drew the same "
                "floor from the same seed, so the section id is not reaching "
                "the floor key")


def test_goldens_are_well_formed():
    """The cheap integrity of each golden, read straight off the file.

    A golden is a committed artefact, so a hand edit or a bad write has
    to be caught even where the bytes happen to match nothing. The
    anchors are the ones PLAN.md section 2 promises: up, down and warden
    are walkable tiles of this grid, and every other anchor that is
    present is too.
    """
    paths = _golden_paths()
    assert paths, f"no goldens under {GOLDEN_DIR}"
    for path in paths:
        where = path.name
        plan = json.loads(path.read_text(encoding="utf-8"))
        w, h, rows = plan["w"], plan["h"], plan["rows"]
        if plan["gen"] != 3:
            pytest.fail(f"{where}: gen is {plan['gen']}, a golden is a v3 floor")
        if len(rows) != h:
            pytest.fail(f"{where}: {len(rows)} rows, expected h={h}")
        for index, row in enumerate(rows):
            if len(row) != w:
                pytest.fail(f"{where}: row {index} is {len(row)} chars, expected w={w}")
            stray = sorted(set(row) - ALPHABET)
            if stray:
                pytest.fail(f"{where}: row {index} carries {stray}, outside #.ud")
        for name in ("up", "down", "warden"):
            if plan["anchors"][name] is None:
                pytest.fail(f"{where}: the {name} anchor is None")
        for name, tile in plan["anchors"].items():
            if tile is None:
                continue
            x, y = tile
            if not (0 <= x < w and 0 <= y < h):
                pytest.fail(f"{where}: anchor {name} at {tile} is off the {w}x{h} grid")
            if rows[y][x] not in WALKABLE:
                pytest.fail(f"{where}: anchor {name} at {tile} is not a walkable tile")
